typography_spectrum: 0.4042091127485037
color:
  brandStrength: 0.06129352981224656
  lightness: 0.9769394828472286
  saturation: 0.04151478875428438
  rhythmicContrast: 0.5842061429284513
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.8699130155146122
name: Ware Agency
navigation:
  - name: Ware Agency Farmers Page
    url: 'https://agents.farmers.com/ca/fresno/nicholas-ware'
    type: external
  - name: Ware Agency Facebook Page
    url: 'https://www.facebook.com/NWFarmers'
    type: external
title: 'Ware Agency, Farmers Insurance'
description: 'We have your life in mind! '
