typography_spectrum: 0.47968403180129826
color:
  brandStrength: 0.6380699770525098
  lightness: 0.38123694993555546
  saturation: 0.6728517359588295
  rhythmicContrast: 0.618555850815028
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.336352386046201
author:
  name: Nick Ware
  email: nware@farmersagent.com
  url: 'https://agents.farmers.com/ca/fresno/nicholas-ware'
name: Ware Agency
navigation:
  - name: Latest Blog Post
    id: da403bbe-3405-4d86-a86c-375228d9ab5d
    type: content
  - name: Ware Agency Facebook Page
    url: 'https://www.facebook.com/NWFarmers'
    type: external
  - name: Ware Agency Youtube Channel
    url: 'https://www.youtube.com/channel/UC6gR-3tCi7rly456XWyaH2A'
    type: external
  - name: Ware Agency Farmers Page
    url: 'https://agents.farmers.com/ca/fresno/nicholas-ware'
    type: external
title: 'Ware Agency, Farmers Insurance'
description: 'We have your life in mind! '
